services:
    jekyll:
        image: jekyll/jekyll:3.5.2
        command: bash -c "bundle install && bundle exec jekyll build && jekyll serve --watch --incremental"
        ports:
            - 4000:4000
        volumes:
            - .:/srv/jekyll
